# Generated by Django 3.2.5 on 2021-07-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagesrc',
            field=models.CharField(max_length=512, verbose_name='이미지주소'),
        ),
    ]
