# Generated by Django 2.2.1 on 2021-07-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Duser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=32, verbose_name="사용자아이디")),
                ("useremail", models.EmailField(max_length=128, verbose_name="사용자이메일")),
                ("password", models.CharField(max_length=64, verbose_name="비밀번호")),
                (
                    "registered_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자",
                "db_table": "duser",
            },
        ),
    ]
